// <auto-generated />
namespace Task_MessageRepo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class migrat314 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migrat314));
        
        string IMigrationMetadata.Id
        {
            get { return "201906161124114_migrat314"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
