// <auto-generated />
namespace Task_MessageRepo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class migrat281 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migrat281));
        
        string IMigrationMetadata.Id
        {
            get { return "201906141519454_migrat281"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
